/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package other.features.jpanels;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author irv
 */
public class customMessage_Screen extends javax.swing.JFrame {

    /**
     * Creates new form customMessage_Screen
     */
    
    public static JLabel msg = new JLabel();
    
    public customMessage_Screen() {
        initComponents();
        String x = msg.getText();
        JOptionPane.showMessageDialog(null, x);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Message");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
