/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package other.features.jpanels;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import login.connection_db;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class history_logs extends javax.swing.JPanel {

    Connection conn_db = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    String mon;
    /**
     * Creates new form history_logs
     */
    public history_logs() {
        initComponents();
        
        conn_db = connection_db.ConnectDB();
        
        fillTable();
    }
    
    public void fillTable(){
        try{
            String sql = "SELECT `user`.`type` as `User`, hour as `Hour`, minute as `Minute`, am_pm as `AM/PM`, day as `Day`, month as `Month`, year as `Year` FROM `user_logs` INNER JOIN `user` ON `user_logs`.`user_id` = `user`.`user_id`";
            ps = conn_db.prepareStatement(sql);
            rs = ps.executeQuery();
            t.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void fillTablebyDate(){
        int records = 0;
        try{
            String sql = "SELECT `user`.`type` as `User`, hour as `Hour`, minute as `Minute`, am_pm as `AM/PM`, day as `Day`, month as `Month`, year as `Year` FROM `user_logs` INNER JOIN `user` ON `user_logs`.`user_id` = `user`.`user_id` where `user_logs`.`month` ='"+mon+"'";
            ps = conn_db.prepareStatement(sql);
            rs = ps.executeQuery();
            t.setModel(DbUtils.resultSetToTableModel(rs));
     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(t);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 115, 701, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Options");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 210, 20));

        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 100, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setText("View by Month");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String x = jComboBox2.getSelectedItem().toString();
        mon = x;
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fillTablebyDate();
        if(t.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No retrieved data!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
