/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package other.features.jpanels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import login.connection_db;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class view_profiles extends javax.swing.JPanel {
    
    Connection conn_db = null;
    ResultSet rs = null;
    PreparedStatement ps = null;

    /**
     * Creates new form view_profiles
     */
    public view_profiles() {
        initComponents();
        
        conn_db = connection_db.ConnectDB();
        
        getallProfile();
    }
    
    public void getallProfile(){
        try{
            String sql = "SELECT first_name, title_name as `First Name`, middle_name as `Middle Name`, last_name as `Last Name` FROM owner";
            ps = conn_db.prepareStatement(sql);
            rs = ps.executeQuery();
            t.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(t);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 115, 701, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
