/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emr.jpanels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import login.connection_db;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Main_Menu_Registration extends javax.swing.JPanel {
    
    Connection conn_db = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    JComboBox s = new JComboBox();
    
    int count=0;
    
    /*********for search names************/
    String searchlname;
    String searchfname;
    String searchmname="";
    
    String upoid;
    /*********for search names************/
    /**
     * Creates new form start_tab
     */
    public Main_Menu_Registration() {
        initComponents();
        
        conn_db = connection_db.ConnectDB();
        
        new_profile t1 = new new_profile();
        new_pet t2 = new new_pet();
        jTabbedPane1.addTab("Pet Owner Information", t1);
        jTabbedPane1.addTab("Pet Information", t2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 1220, 580));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
