/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.jpanels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import login.connection_db;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asus
 */
public class itemprice_history extends javax.swing.JFrame {

   Connection conn_db = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    
      String getClassName111;
      String getClassName112;
      String getClassName11;
     int getClassIDqty;
     int iID;
     int getSuppIDitem;
    
    public itemprice_history() {
        initComponents();
        conn_db = connection_db.ConnectDB();
        setCMBSupplierName();
        
    }
     public void setCMBSupplierName(){
            
         try{
             String sql = "SELECT * FROM `supplier` ";
             ps = conn_db.prepareStatement(sql);
             rs = ps.executeQuery();
             
             while(rs.next()){
                jComboBox13.addItem(rs.getString("name"));
                
             }
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
     }
    public void Jlist11(){
               String x = ((DefaultListModel)class_item_list2.getModel()).getElementAt(class_item_list2.getSelectedIndex()).toString();
                getClassName111 = x;
       }
     public void Jlist12(){
               String x = ((DefaultListModel)class_item_list1.getModel()).getElementAt(class_item_list1.getSelectedIndex()).toString();
                getClassName11 = x;
       }
//     public void getClassIDqty(){
//                try{
//                       String sql1 ="select classification_id from classification1 where name='"+getClassName111+"'";
//                       ps=conn_db.prepareStatement(sql1);
//                       rs = ps.executeQuery();
//
//                       while(rs.next()){
//                           getClassIDqty = rs.getInt("classification_id");
//                           //JOptionPane.showMessageDialog(null,getClassIDqty );
//                           System.out.println(getClassIDqty); }
//                   } catch(Exception e){
//                       JOptionPane.showMessageDialog(null, e);}
//     }
                
        
        
     public void showInTable(){
        try{
            String sql="select item_name AS `Item Name`, prevsupPrice AS `Previous Supplier Price`,newsupp_price AS `New Supplier Price`, prevSalePrice AS `Previous Sale Price`,inc_per AS `Increased Percentage`, newsale_price AS `New Sale Price`, concat_ws(' ',dayUpdated, moUpdated, yrUpdated) as `Date Updated` from iprice_history where item_name ='"+ getClassName11 +"'";
       //     String sql = "select  iprice_history.item_name as `Item Name`,  iprice_history.prevsupPrice as `Previous Supplier Price`, iprice_history.newsupp_price AS `New Supplier Price`, iprice_history.prevSalePrice AS `Previous Sale Price`, iprice_history.inc_per AS `Increased Percentage`, iprice_history.newsale_price AS `New Sale Price`, CONCAT_WS(' ', iprice_history.dayUpdated,iprice_history.moUpdated,iprice_history.yrUpdated) AS `Date Updated` from iprice_history inner join item on item.name = iprice_history.item_name where item_name ='"+class_item_list1.getSelectedIndex().toString()+"'";
            ps = conn_db.prepareStatement(sql);
            rs = ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));}
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }
        
        if(jTable1.getModel().getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No data retrieved");
        }
        
     }
   
    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jComboBox13 = new javax.swing.JComboBox();
        jButton19 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        class_item_list1 = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        class_item_list2 = new javax.swing.JList();
        jButton20 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Supplier", 0, 0, new java.awt.Font("Georgia", 0, 14))); // NOI18N
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });
        jComboBox13.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox13PropertyChange(evt);
            }
        });
        jPanel21.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, -1));

        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton19.setText("View");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        class_item_list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                class_item_list1MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(class_item_list1);

        jPanel21.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, 80));

        class_item_list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                class_item_list2MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(class_item_list2);

        jPanel21.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 190, 90));

        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton20.setText("View");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Item Name");
        jPanel21.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 20));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Classification Name");
        jPanel21.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 20));

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(897, 897, 897)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
           

    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jComboBox13PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox13PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13PropertyChange

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
     
          try{
                       String sql1 ="select classification_id from classification1 where name='"+getClassName111+"'";
                       ps=conn_db.prepareStatement(sql1);
                       rs = ps.executeQuery();

                       while(rs.next()){
                           getClassIDqty = rs.getInt("classification_id");
                           //JOptionPane.showMessageDialog(null,getClassIDqty );
                           System.out.println(getClassIDqty); }
                   } catch(Exception e){
                       JOptionPane.showMessageDialog(null, e);}
          
          DefaultListModel dimx1 = new DefaultListModel();
//          String cont = "";
//          dimx1.addElement(cont);
          class_item_list1.setModel(dimx1);
          
          try{
               String sql1 ="SELECT * FROM `item` INNER JOIN supplier ON supplier.supplier_id = item.supplier_id INNER JOIN classification1 ON `item`.`classification_id` = `classification1`.`classification_id` WHERE supplier.name ='"+jComboBox13.getSelectedItem().toString()+"' AND classification1.name = '"+class_item_list2.getSelectedValue().toString()+"'";
            ps=conn_db.prepareStatement(sql1);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String getClassificationName = rs.getString("name");
                String getItemId = rs.getString("item.item_id");
                jLabel1.setText(getItemId);
                String getClassId = rs.getString("classification1.classification_id");
                jLabel2.setText(getClassId);
               String getSupID = rs.getString("supplier.supplier_id");
               jLabel3.setText(getSupID);
               dimx1.addElement(getClassificationName);
               class_item_list1.setModel(dimx1);
  
                }
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
          }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void class_item_list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_item_list1MouseClicked
        Jlist12();
        showInTable();
    }//GEN-LAST:event_class_item_list1MouseClicked

    private void class_item_list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_item_list2MouseClicked
        Jlist11();
    }//GEN-LAST:event_class_item_list2MouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try{
                String sql1 ="select supplier_id from supplier where name='"+jComboBox13.getSelectedItem()+"'";
                ps=conn_db.prepareStatement(sql1);
                rs = ps.executeQuery();

                    while(rs.next()){
                     getSuppIDitem = rs.getInt("supplier_id");
                   //  JOptionPane.showMessageDialog(null,getSuppIDitem );
                      System.out.println( getSuppIDitem); }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e); }
        
       DefaultListModel ewan = new DefaultListModel();
            try{
                String sql="select name from classification1 where supplier_id= '"+ getSuppIDitem+"'";
                ps = conn_db.prepareStatement(sql);
                rs = ps.executeQuery();

                    while(rs.next()){
                        String getname1 = rs.getString("name");  
                        ewan.addElement(getname1);
                        class_item_list2.setModel(ewan);}    
            }catch(Exception e){     
                JOptionPane.showMessageDialog(null, e);}  
    }//GEN-LAST:event_jButton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemprice_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemprice_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemprice_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemprice_history.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itemprice_history().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList class_item_list1;
    private javax.swing.JList class_item_list2;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
