/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory.jpanels;

import static inventory.jpanels.Main_Menu_Inventory.jTable5;
import static inventory.jpanels.Main_Menu_Inventory.jTextField13;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.connection_db;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author asus
 */
public class lost_damage_items extends javax.swing.JFrame {
   
    Connection conn_db = null;
     ResultSet rs = null;
    PreparedStatement ps = null;
    
     String getClassName111;
      String getClassName112;
      String getClassName11;
     int getClassIDqty;
     int iID;
     int getSuppIDitem;
    
   
    public lost_damage_items() {
        initComponents();
        conn_db = connection_db.ConnectDB();
        setCMBSupplierName();
    }

    
     public void setCMBSupplierName(){
            
         try{
             String sql = "SELECT * FROM `supplier` ";
             ps = conn_db.prepareStatement(sql);
             rs = ps.executeQuery();
             
             while(rs.next()){
                jComboBox13.addItem(rs.getString("name"));
                
             }
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
     }
    public void Jlist11(){
               String x = ((DefaultListModel)class_item_list2.getModel()).getElementAt(class_item_list2.getSelectedIndex()).toString();
                getClassName111 = x;
       }
     public void Jlist12(){
               String x = ((DefaultListModel)class_item_list1.getModel()).getElementAt(class_item_list1.getSelectedIndex()).toString();
                getClassName11 = x;
       }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jComboBox13 = new javax.swing.JComboBox();
        jButton19 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        class_item_list1 = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        class_item_list2 = new javax.swing.JList();
        jButton20 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 0, 14))); // NOI18N
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });
        jComboBox13.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox13PropertyChange(evt);
            }
        });
        jPanel21.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, -1));

        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton19.setText("View");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        class_item_list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                class_item_list1MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(class_item_list1);

        jPanel21.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, 80));

        class_item_list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                class_item_list2MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(class_item_list2);

        jPanel21.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 190, 90));

        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton20.setText("View");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Item Name");
        jPanel21.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 20));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Damaged/Lost Quantity");
        jPanel21.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 140, 20));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("Classification Name");
        jPanel21.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 20));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel21.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 60, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "......", "Damage", "Lost" }));
        jPanel21.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 120, 30));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("Current Quantity");
        jPanel21.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 100, 20));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Remarks");
        jPanel21.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 60, 20));
        jPanel21.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 60, 30));

        jLabel1.setText("jLabel1");
        jPanel21.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 0, 10));

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 120, 30));

        jLabel3.setText("jLabel3");
        jPanel21.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 0));

        jLabel4.setText("jLabel3");
        jPanel21.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, 0));

        jLabel5.setText("jLabel3");
        jPanel21.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 34, -1, 0));

        jLabel6.setText("jLabel3");
        jPanel21.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed

    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jComboBox13PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox13PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13PropertyChange

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        try{
            String sql1 ="select classification_id from classification1 where name='"+getClassName111+"'";
            ps=conn_db.prepareStatement(sql1);
            rs = ps.executeQuery();

            while(rs.next()){
                getClassIDqty = rs.getInt("classification_id");
                //JOptionPane.showMessageDialog(null,getClassIDqty );
                System.out.println(getClassIDqty); }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}

        DefaultListModel dimx1 = new DefaultListModel();
        //          String cont = "";
        //          dimx1.addElement(cont);
        class_item_list1.setModel(dimx1);

        try{
            String sql1 ="SELECT * FROM `item` INNER JOIN supplier ON supplier.supplier_id = item.supplier_id INNER JOIN classification1 ON `item`.`classification_id` = `classification1`.`classification_id` WHERE supplier.name ='"+jComboBox13.getSelectedItem().toString()+"' AND classification1.name = '"+class_item_list2.getSelectedValue().toString()+"'";
            ps=conn_db.prepareStatement(sql1);
            rs = ps.executeQuery();

            while(rs.next()){
                String getClassificationName = rs.getString("name");
                String getItemId = rs.getString("item.item_id");
                jLabel5.setText(getItemId);
                String getClassId = rs.getString("classification1.classification_id");
                jLabel3.setText(getClassId);
                String getSupID = rs.getString("supplier.supplier_id");
                jLabel4.setText(getSupID);
                dimx1.addElement(getClassificationName);
                class_item_list1.setModel(dimx1);

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void class_item_list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_item_list1MouseClicked
        Jlist12();
       
        try{
             String sql="select quantity from item where name ='"+ getClassName11 +"'";
             ps = conn_db.prepareStatement(sql);
             rs = ps.executeQuery();
             
             while(rs.next()){
                jTextField2.setText(rs.getString("quantity"));
                
             }
             
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
        
        
//        showInTable();
    }//GEN-LAST:event_class_item_list1MouseClicked

    private void class_item_list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_item_list2MouseClicked
        Jlist11();
    }//GEN-LAST:event_class_item_list2MouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try{
            String sql1 ="select supplier_id from supplier where name='"+jComboBox13.getSelectedItem()+"'";
            ps=conn_db.prepareStatement(sql1);
            rs = ps.executeQuery();

            while(rs.next()){
                getSuppIDitem = rs.getInt("supplier_id");
                //  JOptionPane.showMessageDialog(null,getSuppIDitem );
                System.out.println( getSuppIDitem); }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e); }

        DefaultListModel ewan = new DefaultListModel();
        try{
            String sql="select name from classification1 where supplier_id= '"+ getSuppIDitem+"'";
            ps = conn_db.prepareStatement(sql);
            rs = ps.executeQuery();

            while(rs.next()){
                String getname1 = rs.getString("name");
                ewan.addElement(getname1);
                class_item_list2.setModel(ewan);}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String old = jTextField2.getText();
        int old_int = Integer.parseInt(old);
        String qty = jTextField1.getText();
        int qty_int = Integer.parseInt(qty);
        
        int total = old_int - qty_int;
        jLabel1.setText(Integer.toString(total));
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             String x = ((DefaultListModel)class_item_list2.getModel()).getElementAt(class_item_list2.getSelectedIndex()).toString();
              String y = ((DefaultListModel)class_item_list2.getModel()).getElementAt(class_item_list2.getSelectedIndex()).toString();
        try{
                String sql = "Insert into lostdamage_items (`item_name`,`item_class`,`item_supp`,`qty`,`remarks`) values (?,?,?,?,?)";
                ps=conn_db.prepareStatement(sql);
                ps.setString(1, x);
                ps.setString(2, y);
                ps.setString(3, jComboBox13.getSelectedItem().toString());
                ps.setString(4, jTextField1.getText());
                ps.setString(5, jComboBox1.getSelectedItem().toString());
                ps.execute();  
                
                 JOptionPane.showMessageDialog(null, "Succesfully Done");
                 
                 
                
            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);

            }
             ////////to quantity/////
             try{
                String sql="UPDATE item SET quantity=?";         
            ps=conn_db.prepareStatement(sql);
                ps.setString(1, jLabel1.getText());
                ps.executeUpdate();       
             
                
            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);

            }
             
             
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lost_damage_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lost_damage_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lost_damage_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lost_damage_items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lost_damage_items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList class_item_list1;
    private javax.swing.JList class_item_list2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
