/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package maintenance.jpanels;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.connection_db;

/**
 *
 * @author irv
 */
public class services_classification_frame extends javax.swing.JFrame {
Connection conn_db = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    String classid;
    /**
     * Creates new form services_classification_frame
     */
    public services_classification_frame() {
        initComponents();
        conn_db = connection_db.ConnectDB();
        
        update.setEnabled(false);
        save.setEnabled(true);
        
        //for centered frame////
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        //
    }
    
    public void getClassID(){
        try{
            String sql = "select * from services_classifications where classification_name ='"+txt_class.getText()+"'";
            ps = conn_db.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
                String getID = rs.getString("classification_id");
                classid = getID;
            }
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
         }
     
      public void container(){
      
        txt_class.getText();
       
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_class = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        class_jtbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Classification");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txt_class.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_class.setForeground(new java.awt.Color(51, 102, 0));
        txt_class.setText("*Classification");
        txt_class.setToolTipText("Classification Name");
        txt_class.setBorder(javax.swing.BorderFactory.createTitledBorder("Classification Name"));
        txt_class.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_classMouseClicked(evt);
            }
        });
        txt_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_classActionPerformed(evt);
            }
        });
        txt_class.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_classFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_classFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Classification");

        class_jtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Classification"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        class_jtbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                class_jtblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(class_jtbl);

        jLabel1.setText(" ");

        jToolBar1.setRollover(true);

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Clear Green Button.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jToolBar1.add(save);

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Write Document.png"))); // NOI18N
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jToolBar1.add(update);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Gear.png"))); // NOI18N
        jButton1.setText("Manage Service Price Update");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Gear.png"))); // NOI18N
        jButton2.setText("Manage Services");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txt_class, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(txt_class, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_classMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_classMouseClicked

    }//GEN-LAST:event_txt_classMouseClicked

    private void txt_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_classActionPerformed

    private void txt_classFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_classFocusGained
        if(txt_class.getText().equals("*Classification")){
            txt_class.setText("");
            txt_class.setForeground(Color.BLACK);
        }else{

        }
    }//GEN-LAST:event_txt_classFocusGained

    private void txt_classFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_classFocusLost
        if(txt_class.getText().equals("")){
            txt_class.setText("*Classification");
            txt_class.setForeground(new Color(51,102,0));
        }else{
        }
    }//GEN-LAST:event_txt_classFocusLost

    private void class_jtblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_jtblMouseClicked

        DefaultTableModel model=(DefaultTableModel) class_jtbl.getModel();
        txt_class.setText((String) model.getValueAt(class_jtbl.getSelectedRow(), 0));

        getClassID();
        
        update.setEnabled(true);
        save.setEnabled(false);
    }//GEN-LAST:event_class_jtblMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked

    }//GEN-LAST:event_updateMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try{
            String sql="UPDATE services_classifications SET classification_name=? where classification_id= ? ";
            ps=conn_db.prepareStatement(sql);

            ps.setString(1, txt_class.getText());
            ps.setString(2, classid);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Classification Successfully Updated!");

        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);
        }

        DefaultTableModel model=(DefaultTableModel) class_jtbl.getModel();
        model.setValueAt(txt_class.getText(), class_jtbl.getSelectedRow(), 0);

        txt_class.setText("");
        
        update.setEnabled(false);
        save.setEnabled(true);
    }//GEN-LAST:event_updateActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if(txt_class.getText().equals("*Classification")){
            JOptionPane.showMessageDialog(rootPane, "Empty field(s) detected","Validation",JOptionPane.INFORMATION_MESSAGE);
        }else{
            save.setEnabled(true);
        update.setEnabled(false);

        jLabel1.setText("");

            DefaultTableModel model=(DefaultTableModel) class_jtbl.getModel();
            model.addRow(new Object[] {txt_class.getText(),});

            try{
                String sql2 = "insert into services_classifications (classification_name)values(?)";
                ps=conn_db.prepareStatement(sql2);
                ps.setString(1, txt_class.getText());
                ps.execute();

                JOptionPane.showMessageDialog(null, "Classification Successfully Saved!");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e) ;
            }
            update.setEnabled(true);
            txt_class.setText("");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new service_priceupdate_frame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new services_update_frame().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(services_classification_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(services_classification_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(services_classification_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(services_classification_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new services_classification_frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable class_jtbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton save;
    private javax.swing.JTextField txt_class;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
