/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maintenance.jpanels;

import com.toedter.calendar.JCalendar;
import static home.home_vet.date_today;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import login.connection_db;

/**
 *
 * @author asus
 */
public class services_update_frame extends javax.swing.JFrame {

    Connection conn_db = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    String getServices;
    String cid;
    String getServiceName;
    String day;
    String month;
    String year;
    
    public services_update_frame() {
        initComponents();
        
        bUpdate.setEnabled(false);
        
        //for centered frame////
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        //
        
         conn_db = connection_db.ConnectDB();
         autodate();
         
    
    ///***********COMBO BOC SERVICE CLASSIFICATION*******************/// 
         try{
         String sql1 = "select * from services_classifications";
         ps = conn_db.prepareStatement(sql1);
         rs = ps.executeQuery();
         
         while(rs.next()) {
             String getService_Name = rs.getString("classification_name");
             cb_sc.addItem(getService_Name);
         }
     }
     catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);}
    
    ///////********************************************//////////
    
    //COMBO BOX SERVICE NAME*****
     try{
         String sql1 = "select * from services_data";
         ps = conn_db.prepareStatement(sql1);
         rs = ps.executeQuery();
         
         while(rs.next()) {
             String getService_Name = rs.getString("name");
             cb_sn.addItem(getService_Name);
         }
     }
     catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
     }
     
    }
    
    
    public void autodate(){
        String timeStamp = new SimpleDateFormat("d MMM yyyy").format(Calendar.getInstance().getTime());
        date.setText(timeStamp.toUpperCase());
    }
 public void container(){
            cb_sn.getSelectedItem();
              }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_sn = new javax.swing.JTextField();
        cb_sc = new javax.swing.JComboBox();
        cb_sn = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        bUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Services Update");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 65, 216, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Service Classification");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 156, 160, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Service Name");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 205, 150, 30));

        txt_sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_snActionPerformed(evt);
            }
        });
        getContentPane().add(txt_sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 204, 200, 30));

        cb_sc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        cb_sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_scActionPerformed(evt);
            }
        });
        getContentPane().add(cb_sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 155, 200, 30));

        cb_sn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        cb_sn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_snMouseClicked(evt);
            }
        });
        cb_sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_snActionPerformed(evt);
            }
        });
        getContentPane().add(cb_sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 103, 200, 30));

        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 306, 40, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Select Service Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 103, 172, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Date:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 65, 77, -1));

        jToolBar1.setRollover(true);

        bUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Write Document.png"))); // NOI18N
        bUpdate.setText("Update");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        jToolBar1.add(bUpdate);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 564, 47));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed

        
        if ( JOptionPane.showConfirmDialog(new JFrame(),
            "Are you sure you want to Update this Service?",
            "Updating Service", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        jLabel1.setText("");

            String str = date.getText();
            String[] parts = str.split(" ");
            String p1 = parts[0]; // 004
            String p2 = parts[1]; // 034556
            String p3 = parts[2]; // 034556

            day = p1;
            month = p2;
            year = p3;

            try{
                String sql="UPDATE services_data SET classification=?, name=?,day_updated=?,  month_updated=?, year_updated=?  where service_id = '"+ cid+"'";
                ps=conn_db.prepareStatement(sql);
                ps.setString(1, cb_sc.getSelectedItem().toString());
                ps.setString(2, txt_sn.getText());
                ps.setString(3, day);
                ps.setString(4, month);
                ps.setString(5, year);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Service Successfully Updated!");

            }
            catch(Exception e){

                JOptionPane.showMessageDialog(null, e);}
        cb_sn.setSelectedIndex(0);
        cb_sc.setSelectedIndex(0);
        
        bUpdate.setEnabled(false);
        
        txt_sn.setText("");
    }//GEN-LAST:event_bUpdateActionPerformed
    }
    private void cb_scActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_scActionPerformed
        
      
    }//GEN-LAST:event_cb_scActionPerformed

    private void cb_snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_snActionPerformed
        String cmb = (String) cb_sn.getSelectedItem();
        String sql = "Select classification, name from services_data where name=?";
         try {
             
                ps = conn_db.prepareStatement(sql);
                ps.setString(1, cmb);
                rs = ps.executeQuery();
                
                    if  (rs.next()){
                    String clss = rs.getString ("classification");
                    cb_sc.setSelectedItem(clss.toUpperCase());
                    String nme = rs.getString ("name");
                    txt_sn.setText(nme);
                    
                }              
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        String Y = cb_sc.getSelectedItem().toString();
        Y= getServices;

        String Z = cb_sn.getSelectedItem().toString();
        Z= getServiceName;
       
        bUpdate.setEnabled(true);
        
    }//GEN-LAST:event_cb_snActionPerformed

    private void cb_snMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_snMouseClicked
       
    bUpdate.setEnabled(false);
       
    }//GEN-LAST:event_cb_snMouseClicked

    private void txt_snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_snActionPerformed

      
    }//GEN-LAST:event_txt_snActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(services_update_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(services_update_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(services_update_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(services_update_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new services_update_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bUpdate;
    private javax.swing.JComboBox cb_sc;
    private javax.swing.JComboBox cb_sn;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txt_sn;
    // End of variables declaration//GEN-END:variables
}
