/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package temp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import login.connection_db;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author irv
 */
public class view_user_logs extends javax.swing.JFrame {
    
    Connection conn_db = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form view_user_logs
     */
    public view_user_logs() {
       conn_db = connection_db.ConnectDB();
        initComponents();
        jButton2.setEnabled(false);
        showontbl();
        getnextid();
    }
    
    public void showontbl(){
        try{
             String sql = "SELECT user_logs.`log_id` as ID, user.type as User, CONCAT_WS(' ',user_logs.`day`,user_logs.`month`,user_logs.`year`) as Date, CONCAT_WS('',user_logs.`hour`,':',user_logs.`minute`,' ',user_logs.`am_pm`) as Time FROM user_logs inner join user on user_logs.user_id = user.user_id WHERE `log_id` >= '"+jLabel1.getText()+"' ORDER BY `log_id` LIMIT 0,10";
             ps = conn_db.prepareStatement(sql);
             rs = ps.executeQuery();
             jTable1.setModel(DbUtils.resultSetToTableModel(rs));         
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }

    }
    
     public void showontblprev(){
        try{
             String sql = "SELECT user_logs.`log_id` as ID, user.type as User, CONCAT_WS(' ',user_logs.`day`,user_logs.`month`,user_logs.`year`) as Date, CONCAT_WS('',user_logs.`hour`,':',user_logs.`minute`,' ',user_logs.`am_pm`) as Time FROM user_logs inner join user on user_logs.user_id = user.user_id WHERE `log_id` between '"+jLabel2.getText()+"' and '"+jLabel4.getText()+"' ORDER BY `log_id` LIMIT 0,10";
             ps = conn_db.prepareStatement(sql);
             rs = ps.executeQuery();
             jTable1.setModel(DbUtils.resultSetToTableModel(rs));         
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
    }
    
    public void getnextid(){
        jButton2.setEnabled(true);
        int row = jTable1.getRowCount();
        jLabel1.setText(jTable1.getValueAt(row-1, 0).toString());
    }
    
    public void getprevid(){
        try{
            int row = jTable1.getRowCount();
            jLabel1.setText(jTable1.getValueAt(row-10, 0).toString());

            int getbase1 = Integer.parseInt(jTable1.getValueAt(row-10, 0).toString());
            jLabel4.setText(Integer.toString(getbase1));

            int getbase2 = getbase1-9;
            jLabel2.setText(Integer.toString(getbase2));
            
            if(Integer.parseInt(jLabel2.getText())<=2){
            jButton2.setEnabled(false);
            jLabel1.setText("1");
            }
        }catch(Exception e){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 82, 563, 360));

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 132, -1));

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 132, -1));

        jLabel1.setText("1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jLabel2.setText("0");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        jLabel3.setText("Range 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        jLabel4.setText("0");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel5.setText("Range 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showontbl();
        getnextid();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getprevid();
        showontblprev();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_user_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_user_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_user_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_user_logs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_user_logs().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
